memory_limit = 256M
max_execution_time = 60
upload_max_filesize = 20M
post_max_size = 22M
display_errors = Off
log_errors = On
error_log = /var/log/php/error.log
expose_php = Off
date.timezone = Africa/Johannesburg
